apiVersion: v1
kind: Service
metadata:
  name: node-docker-app-service
spec:
  type: NodePort          # exposes the app on a port on the Minikube node
  selector:
    app: node-docker-app  # must match the label in Deployment
  ports:
    - protocol: TCP
      port: 80            # Service port (inside cluster)
      targetPort: 3000    # Container port (your app)
      nodePort: 30080     # Port on Minikube node (access from Mac)
